// Country name to ISO 3166-1 alpha-2 code mapping
const countryCodes: Record<string, string> = {
  // English
  'china': 'CN',
  'united states': 'US',
  'usa': 'US',
  'germany': 'DE',
  'japan': 'JP',
  'south korea': 'KR',
  'korea': 'KR',
  'united kingdom': 'GB',
  'uk': 'GB',
  'france': 'FR',
  'australia': 'AU',
  'canada': 'CA',
  'brazil': 'BR',
  'india': 'IN',
  'russia': 'RU',
  'italy': 'IT',
  'spain': 'ES',
  'netherlands': 'NL',
  'switzerland': 'CH',
  'sweden': 'SE',
  'norway': 'NO',
  'denmark': 'DK',
  'finland': 'FI',
  'belgium': 'BE',
  'austria': 'AT',
  'poland': 'PL',
  'turkey': 'TR',
  'uae': 'AE',
  'united arab emirates': 'AE',
  'saudi arabia': 'SA',
  'singapore': 'SG',
  'malaysia': 'MY',
  'indonesia': 'ID',
  'thailand': 'TH',
  'vietnam': 'VN',
  'philippines': 'PH',
  'mexico': 'MX',
  'argentina': 'AR',
  'chile': 'CL',
  'colombia': 'CO',
  'south africa': 'ZA',
  'egypt': 'EG',
  'nigeria': 'NG',
  'kenya': 'KE',
  'new zealand': 'NZ',
  'taiwan': 'TW',
  'hong kong': 'HK',
  'portugal': 'PT',
  'greece': 'GR',
  'czech republic': 'CZ',
  'hungary': 'HU',
  'romania': 'RO',
  'ukraine': 'UA',
  'israel': 'IL',
  'pakistan': 'PK',
  'bangladesh': 'BD',
  'ireland': 'IE',
  'peru': 'PE',
  'venezuela': 'VE',
  'croatia': 'HR',
  'slovakia': 'SK',
  'slovenia': 'SI',
  'lithuania': 'LT',
  'latvia': 'LV',
  'estonia': 'EE',
  'luxembourg': 'LU',
  'malta': 'MT',
  'cyprus': 'CY',
  'iceland': 'IS',
  'morocco': 'MA',
  'tunisia': 'TN',
  'algeria': 'DZ',
  'angola': 'AO',
  'ghana': 'GH',
  'ethiopia': 'ET',
  'tanzania': 'TZ',
  'uganda': 'UG',

  // Chinese translations of common names
  '中国': 'CN',
  '美国': 'US',
  '德国': 'DE',
  '日本': 'JP',
  '韩国': 'KR',
  '英国': 'GB',
  '法国': 'FR',
  '澳大利亚': 'AU',
  '加拿大': 'CA',
  '巴西': 'BR',
  '印度': 'IN',
  '俄罗斯': 'RU',
  '意大利': 'IT',
  '西班牙': 'ES',
  '荷兰': 'NL',
  '瑞士': 'CH',
  '瑞典': 'SE',
  '挪威': 'NO',
  '丹麦': 'DK',
  '芬兰': 'FI',
  '比利时': 'BE',
  '奥地利': 'AT',
  '波兰': 'PL',
  '土耳其': 'TR',
  '阿联酋': 'AE',
  '沙特阿拉伯': 'SA',
  '新加坡': 'SG',
  '马来西亚': 'MY',
  '印度尼西亚': 'ID',
  '泰国': 'TH',
  '越南': 'VN',
  '菲律宾': 'PH',
  '墨西哥': 'MX',
  '阿根廷': 'AR',
  '智利': 'CL',
  '哥伦比亚': 'CO',
  '南非': 'ZA',
  '埃及': 'EG',
  '尼日利亚': 'NG',
  '新西兰': 'NZ',
  '台湾': 'TW',
  '香港': 'HK',
  '葡萄牙': 'PT',
  '希腊': 'GR',
  '捷克': 'CZ',
  '匈牙利': 'HU',
  '以色列': 'IL',
  '爱尔兰': 'IE',
  '秘鲁': 'PE',
  '乌克兰': 'UA',
};

export function getCountryFlag(countryName?: string | null): string {
  if (!countryName) return '';
  const code = countryCodes[countryName.trim().toLowerCase()];
  if (!code) return '';
  return String.fromCodePoint(
    ...code.split('').map((c) => 0x1F1E6 + c.charCodeAt(0) - 65)
  );
}

export function formatCountryWithFlag(countryName?: string | null): string {
  const flag = getCountryFlag(countryName);
  if (!flag || !countryName) return countryName || '';
  return `${flag} ${countryName}`;
}
